spring:
  application:
    name: library-management
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 1984

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

      thymeleaf:
        cache: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

server:
  port: 8080

